<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SANDY" failures="1" tests="9" name="Ecommerce Tests" time="145.187" errors="0" timestamp="2024-07-23T12:11:13 IST">
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="verifySignUp" time="13.546">
    <failure type="java.lang.AssertionError" message="expected [Sign up successful] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: expected [Sign up successful] but found [This user already exist.]
at com.ecommerce.pom.EcommercePages.UsersignupPage(EcommercePages.java:139)
at com.ecommerce.test.VerifyEcommercePages.verifySignUp(VerifyEcommercePages.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifySignUp -->
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="verifySignWithBlankSpace" time="8.424"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="verifyLogin" time="4.708"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="verifyInvalidLogin" time="6.363"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="browseProduct" time="7.441"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="navigateProductCatogary" time="14.153"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="navigateProductUsingNext" time="8.82"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="orderProduct" time="42.218"/>
  <testcase classname="com.ecommerce.test.VerifyEcommercePages" name="verifyLogOut" time="12.335"/>
</testsuite> <!-- Ecommerce Tests -->
